### ISSUE TITLE
download everything from an account not working

### ISSUE THREAD

**Issue by pinlias** [Tenpi/soundcloud-download#11]
hey tenpi, tried using the button to download everything but it doesnt work anymore. i try but nothing happens. tried both on chrome and firefox. tried installing the extension again and cleaning cookies but nothing happened.
thanks in advance!!!

**Comment by Tenpi** [comment]
Hello, can you try upgrading to the latest version `v0.3.0`? Otherwise let me know which artist(s) you are having trouble downloading from.

**Comment by pinlias** [comment]
Hey, just tried to reinstall and now it works fine. Thanks a lot for the support!!

**Comment by Tenpi** [comment]
No problem!
