### ISSUE TITLE
User download button does not work in some cases

### ISSUE THREAD

**Issue by KleaTech** [Tenpi/soundcloud-download#17]
Download won't start when I try to download this user's songs: https://soundcloud.com/holasoynetobaby
He has more than 100 songs, but over 100 song downloads are at least start on other pages.
Maybe the reason is the emoji in the artists name.

**Comment by KleaTech** [comment]
Found the actual error message: "Unchecked runtime.lastError: Invalid filename"

**Comment by KleaTech** [comment]
Probably fixed it with pull request 18. Not tested though

**Comment by Tenpi** [comment]
I fail to see how #18 resolves this issue. "Invalid filename" means the filename contains characters that are illegal to use in Windows/Mac/Linux filenames, so the download is rejected. You probably need to find what characters are illegal and add a new `.replace()` to the clean function. It probably is emoji in their name.

Also, please name your pull requests. And test them before submitting them. To test this extension, you need to load is as an "unpacked" extension in your browser. Uninstall the version from the chrome store so there's no conflicts.

**Comment by KleaTech** [comment]
The issue is with the trailing whitespace. 
After clean() `"mandragora! 👽"` becomes `"mandragora! "` (notice whitespace at the end). So filename would be 
`"mandragora! \trackname"`
It's illegal to have a space before the path separator, that's the issue here. So I'm pretty sure the solution works.
I'm saving you the investigation here. But fine, I'll test it myself later today. I tested the concept manually in DevTools already, I was just lazy to create an extension, I've only done a single simple extension years ago.

**Comment by Tenpi** [comment]
Ok, issue was indeed the trailing whitespace. I will merge your pull request.
