### ISSUE TITLE
[FEATURE REQUEST] Track number metadata for songs in playlists and albums?

### ISSUE THREAD

**Issue by obloovoo** [Tenpi/soundcloud-download#22]
I find it really irritating when I download a playlist with 30+ songs only to find that I have to manually number each track. It would be really nice if the track number was included in the metadata of each mp3 in a playlist.

**Comment by Tenpi** [comment]
Probably easy to add, but just an FYI: You should never be doing X task hundreds of times over and over, you can easily write a short script that does this for you. So I recommend learning how to code because it will probably save you a lot of irritations in the future.

**Comment by Tenpi** [comment]
Hi, it *should* have the track number in the metadata in this version -> `v0.3.6`. 

On Mac Finder doesn't seem to show track number metadata, moving to a windows computer to test this would be a hassle so I will just assume it works.
