### ISSUE TITLE
Song titles

### ISSUE THREAD

**Issue by wmc27** [Tenpi/soundcloud-download#23]
Songs keep downloading like this instead of being named the title

![image](https://user-images.githubusercontent.com/105387342/167922899-ec344ef2-1cdc-4359-ab39-16098f54ef0a.png)

**Comment by Tenpi** [comment]
what is this track?

**Comment by wmc27** [comment]
i dont remember the track but it does that with every track i download 
![image](https://user-images.githubusercontent.com/105387342/168344676-d21d147c-bbeb-4af5-b1a0-032f1849ebe5.png)

**Comment by Tenpi** [comment]
Have you tried disabling all other extensions (except for this one), in case one is interfering and renaming the downloads?
